# Setup
title:               VirtualHub Blog
tagline:             'Stories about the tutorials'
description:         'A blog that describes the process and various problems faced during creating tutorial for <a href="https://virtualhub.eu.org" target="_blank">VirtualHub</a>.'
url:                 https://blog.virtualhub.eu.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Legacy Installer
  url:               https://legacyinstaller.pcriot.com
  email:             contact@legacyinstaller.pcriot.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
